import sys
import math
import argparse

HEADER_TEMPLATE = """Xfoil polar. Reynolds number fixed. Mach  number fixed
Polar key,{polar_key}
Airfoil,{airfoil}
Reynolds number,{reynolds}
Ncrit,{ncrit}
Mach,{mach}
Max Cl/Cd,{max_ld:.4f}
Max Cl/Cd alpha,{max_ld_alpha:g}


Alpha,Cl,Cd,Cdp,Cm,Top_Xtr,Bot_Xtr
"""

def parse_xfoil_pacc(lines):
    """
    Parse lines from an XFOIL PACC polar file with columns:
    alpha, Cl, Cd, Cdp, Cm, Top_Xtr, Bot_Xtr
    
    Robust to case variations in the header (CL/CD/CDp/CM) and variable spacing.
    If a formal header isn't found, it will still try to parse any line that
    contains 7 floats in the expected order.
    """
    data = []
    read = False
    for ln in lines:
        raw = ln.rstrip("\n")
        s = raw.strip()
        if not s:
            continue

        # Detect header (case-insensitive)
        low = s.lower()
        if ('alpha' in low and 'cl' in low and 'cd' in low):
            read = True
            continue

        parts = s.replace(',', ' ').split()
        # Try to parse 7 floats
        floats = []
        for tok in parts[:7]:
            try:
                floats.append(float(tok))
            except ValueError:
                floats = None
                break

        if floats and len(floats) == 7:
            a, cl, cd, cdp, cm, tx, bx = floats
            data.append({
                "Alpha": a, "Cl": cl, "Cd": cd, "Cdp": cdp, "Cm": cm, "Top_Xtr": tx, "Bot_Xtr": bx
            })

    return data

def compute_max_ld(data):
    max_ld = -math.inf
    max_a = None
    for r in data:
        cd = r["Cd"]
        if cd <= 0:
            continue
        ld = r["Cl"] / cd
        if ld > max_ld:
            max_ld = ld
            max_a = r["Alpha"]
    if max_ld == -math.inf:
        return 0.0, 0.0
    return max_ld, max_a

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="Input raw XFOIL polar file (from PACC)")
    ap.add_argument("output", help="Output CSV file in AirfoilTools-like format")
    ap.add_argument("--airfoil", default="naca0018-il")
    ap.add_argument("--re", type=int, required=True, help="Reynolds number (e.g., 10000)")
    ap.add_argument("--ncrit", type=int, default=5)
    ap.add_argument("--mach", type=float, default=0.0)
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    data = parse_xfoil_pacc(lines)
    if not data:
        raise SystemExit("No data rows parsed. Make sure file was generated by XFOIL PACC with viscous analysis.")

    max_ld, max_a = compute_max_ld(data)

    polar_key = f"xf-{args.airfoil}-{args.re}-n{args.ncrit}"
    header = HEADER_TEMPLATE.format(
        polar_key=polar_key, airfoil=args.airfoil, reynolds=args.re,
        ncrit=args.ncrit, mach=args.mach, max_ld=max_ld, max_ld_alpha=max_a
    )

    with open(args.output, "w", encoding="utf-8") as out:
        out.write(header)
        for r in data:
            out.write("{Alpha:.3f},{Cl:.4f},{Cd:.5f},{Cdp:.5f},{Cm:.4f},{Top_Xtr:.4f},{Bot_Xtr:.4f}\n".format(**r))

if __name__ == "__main__":
    """
    Generates csv file for airfoil module.
    
    Usage example:
    
    python xfoil_polar_to_airfoiltools.py NACA_0018_10000.txt NACA_0018_10000.csv --airfoil naca0018-il --re 10000 --ncrit 5 --mach 0

    or
    
    python xfoil_polar_to_airfoiltools.py NACA_0018_10000.txt NACA_0018_10000.csv --re 10000
    """
    main()
