import sys
import math
import argparse

HEADER_TEMPLATE = """Xfoil polar. Reynolds number fixed. Mach  number fixed
Polar key,{polar_key}
Airfoil,{airfoil}
Reynolds number,{reynolds}
Ncrit,{ncrit}
Mach,{mach}
Max Cl/Cd,{max_ld:.4f}
Max Cl/Cd alpha,{max_ld_alpha:g}


Alpha,Cl,Cd,Cdp,Cm,Top_Xtr,Bot_Xtr
"""

def parse_xfoil_pacc(lines):
    """
    Lê polares do XFOIL (PACC) em qualquer espaçamento, ignora cabeçalhos
    (case-insensitive) e retorna uma lista de dicionários:
    {Alpha, Cl, Cd, Cdp, Cm, Top_Xtr, Bot_Xtr}
    """
    data = []
    for ln in lines:
        s = ln.strip()
        if not s:
            continue
        low = s.lower()
        # pular linhas de cabeçalho (alpha/cl/cd presentes)
        if ('alpha' in low and 'cl' in low and 'cd' in low):
            continue
        parts = s.replace(',', ' ').split()
        # tentar ler 7 floats
        floats = []
        for tok in parts[:7]:
            try:
                floats.append(float(tok))
            except ValueError:
                floats = None
                break
        if floats and len(floats) == 7:
            a, cl, cd, cdp, cm, tx, bx = floats
            data.append({
                "Alpha": a, "Cl": cl, "Cd": cd, "Cdp": cdp, "Cm": cm,
                "Top_Xtr": tx, "Bot_Xtr": bx
            })
    return data

def normalize_sort_dedup(data, alpha_decimals=3):
    """
    - Arredonda Alpha para 'alpha_decimals' casas para agrupar duplicatas (ex.: 0.000).
    - Em duplicatas, mantém a linha com **menor Cd** (tipicamente mais “limpa”).
    - Retorna lista ordenada por Alpha ascendente.
    """
    by_alpha = {}
    for r in data:
        key = round(r["Alpha"], alpha_decimals)
        if key in by_alpha:
            if r["Cd"] < by_alpha[key]["Cd"]:
                by_alpha[key] = r
        else:
            by_alpha[key] = r
    # ordenar por Alpha (valor original, não o arredondado)
    out = sorted(by_alpha.values(), key=lambda x: x["Alpha"])
    return out

def compute_max_ld(data):
    max_ld = -math.inf
    max_a = None
    for r in data:
        cd = r["Cd"]
        if cd <= 0:
            continue
        ld = r["Cl"] / cd
        if ld > max_ld:
            max_ld = ld
            max_a = r["Alpha"]
    if max_ld == -math.inf:
        return 0.0, 0.0
    return max_ld, max_a

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="Arquivo polar bruto do XFOIL (PACC)")
    ap.add_argument("output", help="Arquivo CSV no formato AirfoilTools-like (sem Url)")
    ap.add_argument("--airfoil", default="naca0018-il")
    ap.add_argument("--re", type=int, required=True, help="Reynolds number (ex.: 40000)")
    ap.add_argument("--ncrit", type=int, default=5)
    ap.add_argument("--mach", type=float, default=0.0)
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    data = parse_xfoil_pacc(lines)
    if not data:
        raise SystemExit("No data rows parsed. Make sure file was generated by XFOIL PACC with viscous analysis.")

    # ordenar e remover duplicatas
    data = normalize_sort_dedup(data, alpha_decimals=3)

    # calcular Max Cl/Cd
    max_ld, max_a = compute_max_ld(data)

    polar_key = f"xf-{args.airfoil}-{args.re}-n{args.ncrit}"
    header = HEADER_TEMPLATE.format(
        polar_key=polar_key, airfoil=args.airfoil, reynolds=args.re,
        ncrit=args.ncrit, mach=args.mach, max_ld=max_ld, max_ld_alpha=max_a
    )

    with open(args.output, "w", encoding="utf-8") as out:
        out.write(header)
        for r in data:
            out.write(
                "{Alpha:.3f},{Cl:.4f},{Cd:.5f},{Cdp:.5f},{Cm:.4f},{Top_Xtr:.4f},{Bot_Xtr:.4f}\n".format(**r)
            )
            
if __name__ == "__main__":
    """
    Generates csv file for airfoil module.
    
    Usage example:
    
    python xfoil_polar_to_airfoiltools.py NACA0018_10000.txt NACA0018_10000.csv --airfoil naca0018-il --re 10000 --ncrit 5 --mach 0

    or
    
    python xfoil_polar_to_airfoiltools.py NACA0018_10000.txt NACA0018_10000.csv --re 10000
    """
    main()
